# Generated by Django 4.0.3 on 2022-03-05 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='dogs.breed'),
        ),
    ]
